# Generated by Django 6.0.3 on 2026-03-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_submission_result_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite para enviar soluciones', null=True),
        ),
    ]
